---
- name: Hostname Test
  hosts: all
  connection: local

  tasks:
  - name: create hostname
    pask_hostname:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      hostname: "switch_ansible"

  - name: rename hostname
    pask_hostname:
      prest_ip: "{{ansible_ssh_host}}"
      prest_port: "{{ansible_ssh_port}}"
      user_id: "{{user_id}}"
      user_pw: "{{user_pw}}"
      hostname: "switch"
